%% This file generates input files for CMG (Created by Yogesh Bansal, 2009)

%% Inputs for this code

    fid=fopen(temp,'wt');
    
    %%
    fprintf(fid,'\n ** 2019-09-18, 10:28:49 AM, svj5235');
    fprintf(fid,'\n RESULTS SIMULATOR GEM 201710');
    fprintf(fid,'\n OUTPRN GRID PRES SG ');
    fprintf(fid,'\n ');
    fprintf(fid,'\n INUNIT FIELD');
    fprintf(fid,'\n WSRF WELL 1');
    fprintf(fid,'\n WSRF GRID TIME');
    fprintf(fid,'\n OUTSRF GRID SO SG SW PRES');
    fprintf(fid,'\n OUTSRF RES NONE');
    fprintf(fid,'\n WPRN GRID TIME');
    fprintf(fid,'\n **  Distance units: ft ');
    fprintf(fid,'\n RESULTS XOFFSET           0.0000');
    fprintf(fid,'\n RESULTS YOFFSET           0.0000');
    fprintf(fid,'\n RESULTS ROTATION           0.0000  **  (DEGREES)');
    fprintf(fid,'\n RESULTS AXES-DIRECTIONS 1.0 -1.0 1.0');
    fprintf(fid,'\n ** ***************************************************************************');
    fprintf(fid,'\n ** Definition of fundamental cartesian grid');
    fprintf(fid,'\n ** ***************************************************************************');
    fprintf(fid,'\n GRID VARI 40 1 40');
    fprintf(fid,'\n KDIR DOWN');
    fprintf(fid,'\n DI IVAR ');
    fprintf(fid,'\n  40*0.075');
    fprintf(fid,'\n DJ JVAR ');
    fprintf(fid,'\n  0.075');
    fprintf(fid,'\n DK ALL ');
    fprintf(fid,'\n  1600*0.25');
    fprintf(fid,'\n DTOP  ');
    fprintf(fid,'\n  40*0');
    fprintf(fid,'\n PERMI KVAR ');
    fprintf(fid,'\n  5*0.001 35*0.1');
    fprintf(fid,'\n **  0 = null block, 1 = active block');
    fprintf(fid,'\n NULL CON            1');
    fprintf(fid,'\n POR KVAR ');
    fprintf(fid,'\n  5*0.1 35*0.3');
    fprintf(fid,'\n PERMJ KVAR ');
    fprintf(fid,'\n  5*0.001 35*0.1');
    fprintf(fid,'\n PERMK KVAR ');
    fprintf(fid,'\n  5*0.001 35*0.1');
    fprintf(fid,'\n **  0 = pinched block, 1 = active block');
    fprintf(fid,'\n PINCHOUTARRAY CON            1');
    fprintf(fid,'\n PRPOR 14.6923');
    fprintf(fid,'\n CPOR 0.00001');
    fprintf(fid,'\n ** Model and number of components');
    fprintf(fid,'\n MODEL PR');
    fprintf(fid,'\n NC 2 2');
    fprintf(fid,'\n COMPNAME ''CO2'' ''H2O'' ');
    fprintf(fid,'\n HCFLAG');
    fprintf(fid,'\n 0 0 ');
    fprintf(fid,'\n TRES 77 ');
    fprintf(fid,'\n MW');
    fprintf(fid,'\n 44.01 18.015 ');
    fprintf(fid,'\n AC');
    fprintf(fid,'\n 0.225 0.344 ');
    fprintf(fid,'\n PCRIT');
    fprintf(fid,'\n 72.8 217.6 ');
    fprintf(fid,'\n VCRIT');
    fprintf(fid,'\n 0.094 0.056 ');
    fprintf(fid,'\n TCRIT');
    fprintf(fid,'\n 304.2 647.3 ');
    fprintf(fid,'\n PCHOR');
    fprintf(fid,'\n 78 52 ');
    fprintf(fid,'\n SG');
    fprintf(fid,'\n 0.818 1 ');
    fprintf(fid,'\n TB');
    fprintf(fid,'\n -109.21 212 ');
    fprintf(fid,'\n HEATING_VALUES');
    fprintf(fid,'\n 0 0 ');
    fprintf(fid,'\n BIN');
    fprintf(fid,'\n 0.2 ');
    fprintf(fid,'\n ');
    fprintf(fid,'\n ROCKFLUID');
    fprintf(fid,'\n RPT 1');
    fprintf(fid,'\n **        Sw         krw      krow');
    fprintf(fid,'\n SWT');
    fprintf(fid,'\n ');
    fprintf(fid,'\n           0.2           0       0.8');
    fprintf(fid,'\n         0.225  0.00117187  0.703125');
    fprintf(fid,'\n          0.25   0.0046875    0.6125');
    fprintf(fid,'\n         0.275   0.0105469  0.528125');
    fprintf(fid,'\n           0.3     0.01875      0.45');
    fprintf(fid,'\n         0.325   0.0292969  0.378125');
    fprintf(fid,'\n          0.35   0.0421875    0.3125');
    fprintf(fid,'\n         0.375   0.0574219  0.253125');
    fprintf(fid,'\n           0.4       0.075       0.2');
    fprintf(fid,'\n         0.425   0.0949219  0.153125');
    fprintf(fid,'\n          0.45    0.117187    0.1125');
    fprintf(fid,'\n         0.475    0.141797  0.078125');
    fprintf(fid,'\n           0.5     0.16875      0.05');
    fprintf(fid,'\n         0.525    0.198047  0.028125');
    fprintf(fid,'\n          0.55    0.229688    0.0125');
    fprintf(fid,'\n         0.575    0.263672  0.003125');
    fprintf(fid,'\n           0.6         0.3         0');
    fprintf(fid,'\n **        Sl         krg      krog');
    fprintf(fid,'\n SLT');
    fprintf(fid,'\n ');
    fprintf(fid,'\n           0.4         0.3         0');
    fprintf(fid,'\n      0.434375    0.263672  0.003125');
    fprintf(fid,'\n       0.46875    0.229688    0.0125');
    fprintf(fid,'\n      0.503125    0.198047  0.028125');
    fprintf(fid,'\n        0.5375     0.16875      0.05');
    fprintf(fid,'\n      0.571875    0.141797  0.078125');
    fprintf(fid,'\n       0.60625    0.117188    0.1125');
    fprintf(fid,'\n      0.640625   0.0949219  0.153125');
    fprintf(fid,'\n         0.675       0.075       0.2');
    fprintf(fid,'\n      0.709375   0.0574219  0.253125');
    fprintf(fid,'\n       0.74375   0.0421875    0.3125');
    fprintf(fid,'\n      0.778125   0.0292969  0.378125');
    fprintf(fid,'\n        0.8125     0.01875      0.45');
    fprintf(fid,'\n      0.846875   0.0105469  0.528125');
    fprintf(fid,'\n       0.88125   0.0046875    0.6125');
    fprintf(fid,'\n      0.915625  0.00117188  0.703125');
    fprintf(fid,'\n          0.95           0       0.8');
    fprintf(fid,'\n INITIAL');
    fprintf(fid,'\n ');
    fprintf(fid,'\n USER_INPUT');
    fprintf(fid,'\n PRES CON           20');
    fprintf(fid,'\n SW CON            1');
    fprintf(fid,'\n ZGLOBALC ''CO2'' CON            0');
    fprintf(fid,'\n ZGLOBALC ''H2O'' CON            1');
    
    fprintf(fid,'\n NUMERICAL');
    fprintf(fid,'\n RUN');
    fprintf(fid,'\n DATE 2019 1 1');
    fprintf(fid,'\n **');
    fprintf(fid,'\n WELL  ''INJ''');
    fprintf(fid,'\n INJECTOR ''INJ''');
    fprintf(fid,'\n INCOMP  SOLVENT  1.0  0.0');
    fprintf(fid,'\n OPERATE  MAX  BHP  30.0  CONT');
    fprintf(fid,'\n **          rad  geofac  wfrac  skin');
    fprintf(fid,'\n GEOMETRY  K  0.005  0.37  1.0  0.0');
    fprintf(fid,'\n       PERF      GEOA  ''INJ''');
    fprintf(fid,'\n ** UBA               ff          Status  Connection  ');
    fprintf(fid,'\n     36 1 38         1.0  OPEN    FLOW-FROM  ''SURFACE''');
    fprintf(fid,'\n **');
    fprintf(fid,'\n WELL  ''PROD''');
    fprintf(fid,'\n PRODUCER ''PROD''');
    fprintf(fid,'\n OPERATE  MIN  BHP  10.0  CONT');
    fprintf(fid,'\n **          rad  geofac  wfrac  skin');
    fprintf(fid,'\n GEOMETRY  K  0.005  0.37  1.0  0.0');
    fprintf(fid,'\n       PERF      GEOA  ''PROD''');
    fprintf(fid,'\n ** UBA              ff          Status  Connection  ');
    fprintf(fid,'\n     4 1 38         1.0  OPEN    FLOW-TO  ''SURFACE''');
    fprintf(fid,'\n DATE 2019 1  2.00000');
    fprintf(fid,'\n STOP');
    fprintf(fid,'\n RESULTS RELPERMCORR NUMROCKTYPE 1');
    fprintf(fid,'\n RESULTS RELPERMCORR CORRVALS 0.2 0.2 0.4 0.4 0.2 0.2 0.05 0.05');
    fprintf(fid,'\n RESULTS RELPERMCORR CORRVALS 0.8 0.3 0.3 -99999 2 2 2 2');
    fprintf(fid,'\n RESULTS RELPERMCORR CORRVALS_HONARPOUR -99999 -99999 -99999 -99999 -99999 -99999 -99999 -99999');
    fprintf(fid,'\n RESULTS RELPERMCORR NOSWC false');
    fprintf(fid,'\n RESULTS RELPERMCORR CALINDEX  0');
    fprintf(fid,'\n RESULTS RELPERMCORR STOP');
    fprintf(fid,'\n ');
    fprintf(fid,'\n RESULTS SPEC ''Permeability K''  ');
    fprintf(fid,'\n RESULTS SPEC SPECNOTCALCVAL -99999   ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 1 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 1');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 2 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 2');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 3 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 3');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 4 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 4');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 5 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 5');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 6 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 6');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 7 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 7');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 8 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 8');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 9 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 9');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 10 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 10');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 11 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 11');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 12 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 12');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 13 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 13');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 14 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 14');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 15 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 15');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 16 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 16');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 17 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 17');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 18 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 18');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 19 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 19');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 20 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 20');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 21 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 21');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 22 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 22');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 23 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 23');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 24 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 24');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 25 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 25');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 26 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 26');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 27 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 27');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 28 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 28');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 29 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 29');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 30 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 30');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 31 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 31');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 32 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 32');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 33 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 33');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 34 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 34');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 35 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 35');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 36 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 36');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 37 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 37');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 38 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 38');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 39 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 39');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 40 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 40');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC SPECKEEPMOD ''YES''');
    fprintf(fid,'\n RESULTS SPEC STOP');
    fprintf(fid,'\n ');
    fprintf(fid,'\n ');
    fprintf(fid,'\n RESULTS SPEC ''Porosity''  ');
    fprintf(fid,'\n RESULTS SPEC SPECNOTCALCVAL -99999      ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 1 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 1');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 2 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 2');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 3 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 3');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 4 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 4');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 5 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 5');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 6 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 6');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 7 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 7');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 8 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 8');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 9 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 9');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 10 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 10');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 11 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 11');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 12 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 12');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 13 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 13');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 14 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 14');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 15 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 15');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 16 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 16');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 17 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 17');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 18 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 18');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 19 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 19');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 20 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 20');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 21 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 21');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 22 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 22');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 23 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 23');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 24 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 24');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 25 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 25');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 26 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 26');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 27 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 27');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 28 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 28');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 29 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 29');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 30 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 30');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 31 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 31');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 32 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 32');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 33 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 33');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 34 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 34');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 35 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 35');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 36 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 36');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 37 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 37');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 38 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 38');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 39 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 39');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 40 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 40');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.3         ');
    fprintf(fid,'\n RESULTS SPEC SPECKEEPMOD ''YES''');
    fprintf(fid,'\n RESULTS SPEC STOP');
    fprintf(fid,'\n ');
    fprintf(fid,'\n ');
    fprintf(fid,'\n RESULTS SPEC ''Permeability I''  ');
    fprintf(fid,'\n RESULTS SPEC SPECNOTCALCVAL -99999      ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 1 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 1');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 2 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 2');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 3 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 3');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 4 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 4');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 5 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 5');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 6 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 6');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 7 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 7');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 8 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 8');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 9 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 9');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 10 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 10');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 11 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 11');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 12 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 12');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 13 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 13');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 14 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 14');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 15 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 15');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 16 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 16');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 17 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 17');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 18 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 18');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 19 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 19');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 20 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 20');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 21 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 21');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 22 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 22');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 23 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 23');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 24 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 24');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 25 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 25');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 26 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 26');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 27 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 27');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 28 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 28');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 29 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 29');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 30 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 30');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 31 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 31');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 32 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 32');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 33 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 33');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 34 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 34');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 35 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 35');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 36 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 36');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 37 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 37');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 38 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 38');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 39 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 39');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 40 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 40');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC SPECKEEPMOD ''YES''');
    fprintf(fid,'\n RESULTS SPEC STOP');
    fprintf(fid,'\n ');
    fprintf(fid,'\n ');
    fprintf(fid,'\n RESULTS SPEC ''Pressure''  ');
    fprintf(fid,'\n RESULTS SPEC SPECNOTCALCVAL -99999      ');
    fprintf(fid,'\n RESULTS SPEC REGION ''All Layers (Whole Grid)''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_WHOLEGRID''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 0');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 20          ');
    fprintf(fid,'\n RESULTS SPEC SPECKEEPMOD ''YES''');
    fprintf(fid,'\n RESULTS SPEC STOP');
    fprintf(fid,'\n ');
    fprintf(fid,'\n ');
    fprintf(fid,'\n RESULTS SPEC ''Permeability J''  ');
    fprintf(fid,'\n RESULTS SPEC SPECNOTCALCVAL -99999      ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 1 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 1');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 2 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 2');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 3 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 3');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 4 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 4');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 5 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 5');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.001       ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 6 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 6');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 7 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 7');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 8 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 8');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 9 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 9');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 10 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 10');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 11 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 11');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 12 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 12');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 13 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 13');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 14 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 14');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 15 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 15');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 16 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 16');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 17 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 17');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 18 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 18');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 19 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 19');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 20 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 20');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 21 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 21');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 22 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 22');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 23 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 23');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 24 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 24');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 25 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 25');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 26 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 26');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 27 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 27');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 28 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 28');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 29 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 29');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 30 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 30');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 31 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 31');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 32 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 32');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 33 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 33');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 34 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 34');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 35 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 35');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 36 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 36');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 37 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 37');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 38 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 38');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 39 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 39');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 40 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 40');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.1         ');
    fprintf(fid,'\n RESULTS SPEC SPECKEEPMOD ''YES''');
    fprintf(fid,'\n RESULTS SPEC STOP');
    fprintf(fid,'\n ');
    fprintf(fid,'\n ');
    fprintf(fid,'\n RESULTS SPEC ''Global Composition$C'' ''H2O''');
    fprintf(fid,'\n RESULTS SPEC SPECNOTCALCVAL -99999      ');
    fprintf(fid,'\n RESULTS SPEC REGION ''All Layers (Whole Grid)''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_WHOLEGRID''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 0');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 1           ');
    fprintf(fid,'\n RESULTS SPEC SPECKEEPMOD ''YES''');
    fprintf(fid,'\n RESULTS SPEC STOP');
    fprintf(fid,'\n ');
    fprintf(fid,'\n ');
    fprintf(fid,'\n RESULTS SPEC ''Water Saturation''  ');
    fprintf(fid,'\n RESULTS SPEC SPECNOTCALCVAL -99999      ');
    fprintf(fid,'\n RESULTS SPEC REGION ''All Layers (Whole Grid)''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_WHOLEGRID''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 0');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 1           ');
    fprintf(fid,'\n RESULTS SPEC SPECKEEPMOD ''YES''');
    fprintf(fid,'\n RESULTS SPEC STOP');
    fprintf(fid,'\n ');
    fprintf(fid,'\n ');
    fprintf(fid,'\n RESULTS SPEC ''Global Composition$C'' ''CO2''  ');
    fprintf(fid,'\n RESULTS SPEC SPECNOTCALCVAL -99999      ');
    fprintf(fid,'\n RESULTS SPEC REGION ''All Layers (Whole Grid)''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_WHOLEGRID''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 0');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0           ');
    fprintf(fid,'\n RESULTS SPEC SPECKEEPMOD ''YES''');
    fprintf(fid,'\n RESULTS SPEC STOP');
    fprintf(fid,'\n ');
    fprintf(fid,'\n ');
    fprintf(fid,'\n RESULTS SPEC ''Grid Thickness''  ');
    fprintf(fid,'\n RESULTS SPEC SPECNOTCALCVAL -99999      ');
    fprintf(fid,'\n RESULTS SPEC REGION ''All Layers (Whole Grid)''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_WHOLEGRID''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 0');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0.25        ');
    fprintf(fid,'\n RESULTS SPEC SPECKEEPMOD ''YES''');
    fprintf(fid,'\n RESULTS SPEC STOP');
    fprintf(fid,'\n ');
    fprintf(fid,'\n ');
    fprintf(fid,'\n RESULTS SPEC ''Grid Top''  ');
    fprintf(fid,'\n RESULTS SPEC SPECNOTCALCVAL -99999      ');
    fprintf(fid,'\n RESULTS SPEC REGION ''Layer 1 - Whole layer''');
    fprintf(fid,'\n RESULTS SPEC REGIONTYPE ''REGION_LAYER''');
    fprintf(fid,'\n RESULTS SPEC LAYERNUMB 1');
    fprintf(fid,'\n RESULTS SPEC PORTYPE 1');
    fprintf(fid,'\n RESULTS SPEC CON 0           ');
    fprintf(fid,'\n RESULTS SPEC SPECKEEPMOD ''YES''');
    fprintf(fid,'\n RESULTS SPEC STOP');
    fprintf(fid,'\n ');
   
    fid=fclose(fid);
    
end